export { RegisterPurchasePage } from './RegisterPurchasePage'
export { MerchantTransactionsPage } from './MerchantTransactionsPage'
export { CatalogPage } from './CatalogPage'
export { MerchantRewardsPage } from './MerchantRewardsPage'
export { MerchantUnassigned } from './MerchantUnassigned'
export { BirthdayPage } from './BirthdayPage'
